// Generated by CoffeeScript 1.6.3
(function() {
  var EasyConfiguration, Extension, configuration, expect, file, path;

  expect = require('chai').expect;

  path = require('path');

  EasyConfiguration = require('../../lib/EasyConfiguration');

  Extension = require('../../lib/Extension');

  file = path.resolve(__dirname + '/../data/config.json');

  configuration = null;

  describe('EasyConfiguration', function() {
    beforeEach(function() {
      return configuration = new EasyConfiguration(file);
    });
    describe('#load()', function() {
      return it('should return loaded configuration without parameters', function() {
        return expect(configuration.load()).to.be.eql({});
      });
    });
    return describe('#addSection()', function() {
      it('should return instance of newly registered section', function() {
        return expect(configuration.addSection('newSection')).to.be.an["instanceof"](Extension);
      });
      return it('should throw exception if section with reserved name is trying to register', function() {
        return expect(function() {
          configuration.addSection('includes');
          return configuration.addSection('parameters');
        }).to["throw"](Error);
      });
    });
  });

}).call(this);
