// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, expect;

  expect = require('chai').expect;

  Helpers = require('../../lib/Helpers');

  describe('Helpers', function() {
    describe('#dirName()', function() {
      return it('should return name of file\'s directory', function() {
        return expect(Helpers.dirName('/var/www/data/something.js')).to.be.equal('/var/www/data');
      });
    });
    return describe('#normalizePath()', function() {
      return it('should return normalized and resolved path', function() {
        return expect(Helpers.normalizePath('/var/www/../www/data/././../../www/data/something.js')).to.be.equal('/var/www/data/something.js');
      });
    });
  });

}).call(this);
