// Generated by CoffeeScript 1.6.2
(function() {
  var EasyConfiguration;

  EasyConfiguration = (function() {
    function EasyConfiguration() {}

    return EasyConfiguration;

  })();

  module.exports = EasyConfiguration;

}).call(this);
