// Generated by CoffeeScript 1.6.2
(function() {
  var Extension;

  Extension = (function() {
    function Extension() {}

    Extension.prototype.configurator = null;

    Extension.prototype.data = null;

    Extension.prototype.setConfigurator = function(configurator) {
      this.configurator = configurator;
    };

    Extension.prototype.setData = function(data) {
      this.data = data;
    };

    Extension.prototype.getConfig = function(defaults) {
      if (defaults == null) {
        defaults = null;
      }
      if (this.data === null) {
        this.configurator.load();
      }
      if (defaults !== null) {
        this.data = this.configurator.merge(this.data, defaults);
      }
      return this.data;
    };

    Extension.prototype.loadConfiguration = function() {
      return this.getConfig();
    };

    return Extension;

  })();

  module.exports = Extension;

}).call(this);
