// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, merge, path;

  merge = require('recursive-merge');

  path = require('path');

  Helpers = (function() {
    function Helpers() {}

    Helpers.dirName = function(path) {
      var num;
      num = path.lastIndexOf('/');
      return path.substr(0, num);
    };

    Helpers.normalizePath = function(path) {
      var part, parts, prev, result, _i, _len;
      parts = path.split('/');
      result = [];
      prev = null;
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (part === '.' || part === '') {
          continue;
        } else if (part === '..' && prev) {
          result.pop();
        } else {
          result.push(part);
        }
        prev = part;
      }
      return '/' + result.join('/');
    };

    Helpers.stringifyParameters = function(parameters, parent) {
      var name, result, type, value;
      if (parent == null) {
        parent = null;
      }
      result = {};
      for (name in parameters) {
        value = parameters[name];
        name = parent === null ? name : parent + '.' + name;
        type = Object.prototype.toString.call(value);
        if (type === '[object Object]') {
          result = merge(result, this.stringifyParameters(value, name));
        } else {
          result[name] = value;
        }
      }
      return result;
    };

    Helpers.expandParameters = function(parameters) {
      var name, parse, result, value;
      parse = function(parameter) {
        var asString, i, param, _i, _len;
        asString = false;
        if (typeof parameter === 'string') {
          asString = true;
          parameter = [parameter];
        }
        for (i = _i = 0, _len = parameter.length; _i < _len; i = ++_i) {
          param = parameter[i];
          parameter[i] = param.replace(/%([a-zA-Z.-_]+)%/g, function(match, variable) {
            if (typeof parameters[variable] === 'undefined') {
              throw new Error('Parameter ' + variable + ' was not found');
            }
            return parse(parameters[variable]);
          });
        }
        if (asString === true) {
          parameter = parameter[0];
        }
        return parameter;
      };
      result = {};
      for (name in parameters) {
        value = parameters[name];
        result[name] = parse(value);
      }
      return result;
    };

    Helpers.expandWithParameters = function(data, parameters) {
      var i, replace, value, _i, _len;
      replace = function(s) {
        return s.replace(/%([a-zA-Z.-_]+)%/g, function(match, variable) {
          if (typeof parameters[variable] === 'undefined') {
            throw new Error('Parameter ' + variable + ' was not found');
          }
          return parameters[variable];
        });
      };
      switch (Object.prototype.toString.call(data)) {
        case '[object String]':
          data = replace(data);
          break;
        case '[object Array]':
          for (i = _i = 0, _len = data.length; _i < _len; i = ++_i) {
            value = data[i];
            data[i] = this.expandWithParameters(value, parameters);
          }
          break;
        case '[object Object]':
          for (i in data) {
            value = data[i];
            data[i] = this.expandWithParameters(value, parameters);
          }
      }
      return data;
    };

    Helpers.objectifyParameters = function(parameters) {
      return parameters;
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
