// Generated by CoffeeScript 1.6.3
(function() {
  var Helpers, merge;

  merge = require('recursive-merge');

  Helpers = (function() {
    function Helpers() {}

    Helpers.dirName = function(path) {
      var num;
      num = path.lastIndexOf('/');
      return path.substr(0, num);
    };

    Helpers.normalizePath = function(path) {
      var part, parts, prev, result, _i, _len;
      parts = path.split('/');
      result = [];
      prev = null;
      for (_i = 0, _len = parts.length; _i < _len; _i++) {
        part = parts[_i];
        if (part === '.' || part === '') {
          continue;
        } else if (part === '..' && prev) {
          result.pop();
        } else {
          result.push(part);
        }
        prev = part;
      }
      return '/' + result.join('/');
    };

    return Helpers;

  })();

  module.exports = Helpers;

}).call(this);
